name: Lint Pull
on: pull

jobs:
  linter-job:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: An√°lisis con Pylint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
      
  
