name: ejemplo-modelo-examen
on: 
  push:
    branches:
      - nueva-caracteristica
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
  
      - name:  Descargar el codigo
        uses: actions/checkout@v4

      - name: Configurar entorno
        uses: actions/setup-python@v6
        with:
          python-version: '3.10?'

      - name: Instalar pytest
        run: pip install pytest

      - name: testeo
        run: pytest test.py

      - name: Construir imagen docker
        uses: docker/build-push-action@v6
        with:
          context: . #usa el directorio actual
          push: false #no hace falta subirla
          tags: ejemplo-modelo-examen-latest
      
  
